SELECT
	C.CD_NF
	,A.CD_VD
	,D.CGC
	,C.CD_FILIAL
	,A.DT_DEVO
	,E.CD_NF_SERIE
	,E.CD_FORN
	,E.CNPJ_DESTINATARIO
	,A.CD_VEND
	,C.VLR_IT
	,C.VLR_DESC
	,C.VLR_TOT_IT
	,A.CD_PROD
	,A.CD_IMP
	,A.QT_IT
	,C.VLR_ICMS_IT
	,C.ALIQ_ICMS
	,C.CST_PIS
	,C.VLR_PIS
	,C.CST_COFINS
	,C.VLR_COFINS
FROM PDV_VD_DEV_EST_PROD_IMP A
JOIN PDV_VD_DEV_EST_PROD_IMP_EST_NF_ENT B
	ON A.CD_EMP = B.CD_EMP
	AND A.CD_FILIAL = B.CD_FILIAL
	AND A.CD_VD = B.CD_VD
	AND A.CD_IT = B.CD_IT
JOIN EST_NF_ENT_IT C
	ON B.CD_EMP = C.CD_EMP
	AND B.CD_FILIAL = C.CD_FILIAL
	AND B.CD_NF = C.CD_NF
	AND B.CD_PROD = C.CD_PROD
JOIN PRC_FILIAL D
	ON A.CD_FILIAL = D.CD_FILIAL
JOIN EST_NF_ENT E
	ON B.CD_EMP = E.CD_EMP
	AND B.CD_FILIAL = E.CD_FILIAL
	AND B.CD_NF = E.CD_NF;