SELECT
    B.CGC AS CNPJ
    ,A.CD_FILIAL AS FILIAL
    ,A.CD_PROD AS PRODUTO
    ,A.QT_EST AS ESTOQUE
    ,A.VLR_CUSTO AS CUSTO
    ,A.DT_ULT_ATU AS ULTIMA_ATUALIZACAO

FROM
EST_PROD_CPL A
JOIN PRC_FILIAL B
	ON A.CD_FILIAL = B.CD_FILIAL;