SELECT
	A.CD_VD AS VENDA
	,A.CD_IT AS ITEM_VENDA
      ,C.DT_VD AS DATA_VENDA
	,A.CD_FILIAL AS FILIAL
	,B.CGC AS CNPJ
	,A.CFOP AS CFOP
	,A.CD_PROD AS PRODUTO
	,A.QT_IT AS QUANTIDADE
	,A.VLR_IT AS PRECO
	,A.VLR_DESC_CAD AS VALOR_DESCONTO_CADASTRO
	,A.VLR_DESC_TOT_RAT AS VALOR_DESCONTO_TOTAL_RATEIO
	,A.VLR_DESC_VERBA AS VALOR_DESCONTO_VERBA
	,A.TOT_IT AS TOTAL_ITEM
	,A.PERC_COMIS AS PORCENTAGEM_COMISSAO
	,A.perc_icms AS PORCENTAGEM_ICMS
	,A.vlr_icms AS VALOR_ICMS
	,A.CST_PIS AS CST_PIS
	,A.VLR_PIS AS VALOR_PIS
	,A.CST_COFINS AS CST_COFINS
	,A.VLR_COFINS AS VALOR_COFINS
	,A.VLR_PMC AS PMC

FROM PDV_VD_IT A
JOIN PRC_FILIAL B
	ON A.CD_FILIAL = B.CD_FILIAL
JOIN PDV_VD C
	ON A.CD_EMP = C.CD_EMP
	AND A.CD_FILIAL = C.CD_FILIAL
	AND A.CD_VD = C.CD_VD;