SELECT
    B.CGC AS CNPJ
    ,A.CD_FILIAL AS FILIAL
    ,A.CD_VD AS VENDA
    ,A.CD_IT AS ITEM_VENDA
    ,C.DT_VD AS MOVIMENTO
    ,C.CD_PROD AS PRODUTO
    ,A.DT_RECEITA AS DATA_RECEITA
    ,A.CD_MEDICO_REC AS CODIGO_CR
    ,D.NR_DOC AS NUMERO_CR
    ,D.NM_MEDICO AS NOME_PRESCRITOR
    ,D.CD_TP_DOC AS TIPO_CR
    ,D.UF_DOC AS ESTADO_CR
    ,C.QT_IT AS QUANTIDADE

FROM PDV_VD_IT_REC A
JOIN PRC_FILIAL B
	ON A.CD_FILIAL = B.CD_FILIAL
JOIN PDV_VD_IT C
	ON A.CD_EMP = C.CD_EMP
	AND A.CD_FILIAL = C.CD_FILIAL
	AND A.CD_VD = C.CD_VD
	AND A.CD_IT = C.CD_IT
JOIN GLB_MEDICOS D
	ON A.CD_MEDICO_REC = D.CD_CTR;