SELECT
	A.CD_VD AS VENDA
	,B.CGC AS CNPJ
	,A.CD_FILIAL AS FILIAL
	,A.CD_CX AS CAIXA
	,A.DT_VD AS DATA_VENDA
	,A.HR_VD AS HORA_VENDA
	,A.ST_VD AS STATUS
	,A.NR_ECF AS NUMERO
	,D.SERIE AS SERIE
	,D.CH_NFE AS CHAVE
	,A.CD_CLI AS CLIENTE
	,A.CD_USU AS VENDEDOR
	,A.VLR_VD AS VALOR_VENDA
	,A.VLR_DESC AS VALOR_DESCONTO
	,A.VLR_DESC_ITENS AS VALOR_DESCONTO_ITENS
	,A.VLR_LIQ_VD AS VALOR_LIQUIDO

FROM PDV_VD A
LEFT
JOIN PRC_FILIAL B
	ON A.CD_FILIAL = B.CD_FILIAL
LEFT
JOIN PDV_VD_PDV_VD_NFCE C
	ON A.CD_EMP = C.CD_EMP
	AND A.CD_FILIAL = C.CD_FILIAL
	AND A.CD_VD = C.CD_VD
 LEFT
 JOIN PDV_VD_NFCE D
	ON C.CD_EMP = D.CD_EMP
	AND C.CD_FILIAL = D.CD_FILIAL
	AND C.CD_NFCE = D.CD_NFCE;